### PR TITLE
Added git ignore file

### PR DESCRIPTION
**Pull request by Jahidul2543**
Please review the latest change @mazharulboni  @sayed1970 @SalmanButt95 @mnransari

### CODE REVIEW

**Review by mazharulboni — APPROVED** [review]
Reviewed

**Review by mnransari — APPROVED** [review]
reviewed

**Review by Jahidul2543 — COMMENTED** [review]
Thanks

**Comment by sayed1970** [comment]
Approved

**Review by sayed1970 — COMMENTED** [review]
Approved

**Pull request merged**
